server:
  port: 9098
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jb2404
    username: root
    password: "{cipher}e98b2a784a9cce68839cb792dca1d370dd824cb5483317a91c1e03c9531c5742"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

info:
  app:
    name: "Food Service"
    description: "This is Food Service. Ready to serve users. This configurations is located in config server.and check refresh end points of actuator"
    version: "1.0 Production"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
